// ─────────────────────────────────────────────────────────────
//  Cinelytics – Data Module
//  30 real, popular movies with TMDB poster/backdrop URLs
// ─────────────────────────────────────────────────────────────

const MOVIES_DATA = [
  {
    id: 1,
    title: "Spider-Man: No Way Home",
    year: 2021,
    rating: 8.2,
    votes: 823456,
    runtime: 148,
    revenue: 1901.2,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    overview: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    mediaService: "Netflix",
    continueWatching: true,
    progress: 0,
    trending: false,
    topRated: true,
    comingSoon: false
  },
  {
    id: 2,
    title: "Inception",
    year: 2010,
    rating: 8.8,
    votes: 2345678,
    runtime: 148,
    revenue: 836.8,
    certificate: "PG-13",
    genres: ["Action", "Sci-Fi", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    poster: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    mediaService: "HBO Max",
    continueWatching: true,
    progress: 55,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    votes: 2678901,
    runtime: 152,
    revenue: 1004.6,
    certificate: "PG-13",
    genres: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1xGArp.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg",
    mediaService: "HBO Max",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 4,
    title: "John Wick: Chapter 4",
    year: 2023,
    rating: 7.7,
    votes: 412345,
    runtime: 169,
    revenue: 440.1,
    certificate: "R",
    genres: ["Action", "Crime", "Thriller"],
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    overview: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7Q2KRfMRb0Kz.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    mediaService: "Prime",
    continueWatching: false,
    progress: 0,
    trending: true,
    topRated: true,
    comingSoon: false
  },
  {
    id: 5,
    title: "Jumanji: The Next Level",
    year: 2019,
    rating: 6.7,
    votes: 312456,
    runtime: 123,
    revenue: 800.1,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Comedy"],
    director: "Jake Kasdan",
    cast: ["Dwayne Johnson", "Jack Black", "Kevin Hart"],
    overview: "The gang is back but the game has changed. As they return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored.",
    poster: "https://image.tmdb.org/t/p/w500/bB42KDdfWkOvmzmYkmKAhXpbqPI.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
    mediaService: "Netflix",
    continueWatching: true,
    progress: 42,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 6,
    title: "The Shawshank Redemption",
    year: 1994,
    rating: 9.3,
    votes: 2789012,
    runtime: 142,
    revenue: 58.3,
    certificate: "R",
    genres: ["Drama"],
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    overview: "Over the course of several years, two convicts form a friendship, seeking consolation and eventual redemption through basic compassion.",
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    mediaService: "HBO Max",
    continueWatching: true,
    progress: 68,
    trending: false,
    topRated: true,
    comingSoon: false
  },
  {
    id: 7,
    title: "Interstellar",
    year: 2014,
    rating: 8.7,
    votes: 1987654,
    runtime: 169,
    revenue: 701.7,
    certificate: "PG-13",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    overview: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    mediaService: "Prime",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 8,
    title: "Avengers: Endgame",
    year: 2019,
    rating: 8.4,
    votes: 1123456,
    runtime: 181,
    revenue: 2797.5,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Drama"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions and restore balance.",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9SlfilpQRy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    mediaService: "Disney+",
    continueWatching: true,
    progress: 35,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 9,
    title: "Parasite",
    year: 2019,
    rating: 8.5,
    votes: 876543,
    runtime: 132,
    revenue: 266.1,
    certificate: "R",
    genres: ["Comedy", "Drama", "Thriller"],
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    overview: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    mediaService: "Hulu",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 10,
    title: "Oppenheimer",
    year: 2023,
    rating: 8.3,
    votes: 654321,
    runtime: 180,
    revenue: 952.0,
    certificate: "R",
    genres: ["Drama", "Historical", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    mediaService: "Peacock",
    continueWatching: false,
    progress: 0,
    trending: true,
    topRated: false,
    comingSoon: false
  },
  {
    id: 11,
    title: "The Batman",
    year: 2022,
    rating: 7.8,
    votes: 745678,
    runtime: 176,
    revenue: 770.8,
    certificate: "PG-13",
    genres: ["Action", "Crime", "Drama"],
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright"],
    overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyFAJlMF2vwxKMob0o.jpg",
    mediaService: "HBO Max",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 12,
    title: "Dune: Part Two",
    year: 2024,
    rating: 8.5,
    votes: 534567,
    runtime: 166,
    revenue: 714.4,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Austin Butler"],
    overview: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe.",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    mediaService: "HBO Max",
    continueWatching: false,
    progress: 0,
    trending: true,
    topRated: false,
    comingSoon: false
  },
  {
    id: 13,
    title: "RRR",
    year: 2022,
    rating: 7.8,
    votes: 198765,
    runtime: 187,
    revenue: 160.0,
    certificate: "PG-13",
    genres: ["Action", "Drama", "Historical"],
    director: "S.S. Rajamouli",
    cast: ["N.T. Rama Rao Jr.", "Ram Charan", "Ajay Devgn"],
    overview: "A fictitious story about two legendary revolutionaries and their journey away from home before they began fighting for their country in the 1920s.",
    poster: "https://image.tmdb.org/t/p/w500/nEufeZYoSTpGqz7FaF3bIBMlKHs.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/eTmmGj4Gti1bJIBFnEajBvku.jpg",
    mediaService: "Netflix",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: true,
    comingSoon: false
  },
  {
    id: 14,
    title: "Everything Everywhere All at Once",
    year: 2022,
    rating: 7.8,
    votes: 567890,
    runtime: 139,
    revenue: 141.2,
    certificate: "R",
    genres: ["Action", "Adventure", "Comedy"],
    director: "Daniel Kwan, Daniel Scheinert",
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
    overview: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVQdWfNEhdsBt2HHRzlsob4.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    mediaService: "Apple TV+",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 15,
    title: "Léon: The Professional",
    year: 1994,
    rating: 8.5,
    votes: 1198765,
    runtime: 110,
    revenue: 45.3,
    certificate: "R",
    genres: ["Action", "Crime", "Drama"],
    director: "Luc Besson",
    cast: ["Jean Reno", "Gary Oldman", "Natalie Portman"],
    overview: "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.",
    poster: "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/5cJdJMGGhnyAFfBffKfMNpSaJPp.jpg",
    mediaService: "Prime",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: true,
    comingSoon: false
  },
  {
    id: 16,
    title: "Pulp Fiction",
    year: 1994,
    rating: 8.9,
    votes: 2098765,
    runtime: 154,
    revenue: 213.9,
    certificate: "R",
    genres: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    mediaService: "Netflix",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 17,
    title: "The Godfather",
    year: 1972,
    rating: 9.2,
    votes: 1898765,
    runtime: 175,
    revenue: 287.0,
    certificate: "R",
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    overview: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    mediaService: "Prime",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: true,
    comingSoon: false
  },
  {
    id: 18,
    title: "Fight Club",
    year: 1999,
    rating: 8.8,
    votes: 2198765,
    runtime: 139,
    revenue: 101.2,
    certificate: "R",
    genres: ["Drama", "Thriller"],
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    overview: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7Uef6DNknx.jpg",
    mediaService: "Hulu",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 19,
    title: "Forrest Gump",
    year: 1994,
    rating: 8.8,
    votes: 2098712,
    runtime: 142,
    revenue: 678.2,
    certificate: "PG-13",
    genres: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    overview: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
    mediaService: "Peacock",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 20,
    title: "The Matrix",
    year: 1999,
    rating: 8.7,
    votes: 1987654,
    runtime: 136,
    revenue: 463.5,
    certificate: "R",
    genres: ["Action", "Sci-Fi"],
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    overview: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth—the life he knows is the elaborate deception of an evil cyber-intelligence.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    mediaService: "HBO Max",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 21,
    title: "No Time to Die",
    year: 2021,
    rating: 6.8,
    votes: 456789,
    runtime: 163,
    revenue: 774.2,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Thriller"],
    director: "Cary Joji Fukunaga",
    cast: ["Daniel Craig", "Ana de Armas", "Rami Malek"],
    overview: "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
    poster: "https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWPM4rLz56EbXjG.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
    mediaService: "Apple TV+",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: true,
    comingSoon: false
  },
  {
    id: 22,
    title: "Top Gun: Maverick",
    year: 2022,
    rating: 8.2,
    votes: 612345,
    runtime: 130,
    revenue: 1493.2,
    certificate: "PG-13",
    genres: ["Action", "Drama"],
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
    overview: "After thirty years of service as a top naval aviator, Pete 'Maverick' Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/AaV1YIdWKczAILkMDEwElitvpDa.jpg",
    mediaService: "Prime",
    continueWatching: false,
    progress: 0,
    trending: true,
    topRated: false,
    comingSoon: false
  },
  {
    id: 23,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    rating: 9.0,
    votes: 1876543,
    runtime: 201,
    revenue: 1146.0,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    overview: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/pJjIH9QlHY5PiIRU7iNHmAIyjFa.jpg",
    mediaService: "HBO Max",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 24,
    title: "Gladiator",
    year: 2000,
    rating: 8.5,
    votes: 1567890,
    runtime: 155,
    revenue: 460.5,
    certificate: "R",
    genres: ["Action", "Adventure", "Drama"],
    director: "Ridley Scott",
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    overview: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hnd16oG9pY0BsQFjdINR3WVAxAy.jpg",
    mediaService: "Peacock",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 25,
    title: "Whiplash",
    year: 2014,
    rating: 8.5,
    votes: 912345,
    runtime: 106,
    revenue: 49.0,
    certificate: "R",
    genres: ["Drama", "Mystery"],
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
    overview: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    poster: "https://image.tmdb.org/t/p/w500/oPxnRhyAIzJKEUzSRKWOISIDQFE.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1sm.jpg",
    mediaService: "Netflix",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 26,
    title: "The Prestige",
    year: 2006,
    rating: 8.5,
    votes: 1345678,
    runtime: 130,
    revenue: 109.7,
    certificate: "PG-13",
    genres: ["Drama", "Mystery", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"],
    overview: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    poster: "https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/m7dXF3pO7xpOQnWIqLhkigFxZhG.jpg",
    mediaService: "Disney+",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 27,
    title: "Joker",
    year: 2019,
    rating: 8.4,
    votes: 1298765,
    runtime: 122,
    revenue: 1074.3,
    certificate: "R",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic criminal figure.",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YMDNqKIk.jpg",
    mediaService: "HBO Max",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 28,
    title: "Avatar: The Way of Water",
    year: 2022,
    rating: 7.6,
    votes: 498765,
    runtime: 192,
    revenue: 2320.3,
    certificate: "PG-13",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    overview: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    mediaService: "Disney+",
    continueWatching: false,
    progress: 0,
    trending: true,
    topRated: false,
    comingSoon: false
  },
  {
    id: 29,
    title: "Major",
    year: 2022,
    rating: 8.2,
    votes: 45678,
    runtime: 163,
    revenue: 22.5,
    certificate: "PG-13",
    genres: ["Action", "Drama", "Historical"],
    director: "Sashi Kiran Tikka",
    cast: ["Adivi Sesh", "Saiee Manjrekar", "Sobhita Dhulipala"],
    overview: "The life story of Indian Army officer Major Sandeep Unnikrishnan, who was martyred during the November 2008 Mumbai attacks, and traces the events of his life leading up to that fateful day.",
    poster: "https://image.tmdb.org/t/p/w500/plM3MuKICLfMK0a1O3fMHlqJ7RZ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gsQcuoT2cAfaxQMIIAbKq0vPNfF.jpg",
    mediaService: "Netflix",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  },
  {
    id: 30,
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    year: 2022,
    rating: 6.2,
    votes: 234567,
    runtime: 142,
    revenue: 407.2,
    certificate: "PG-13",
    genres: ["Adventure", "Fantasy"],
    director: "David Yates",
    cast: ["Eddie Redmayne", "Jude Law", "Mads Mikkelsen"],
    overview: "Professor Albus Dumbledore knows the powerful Dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts Magizoologist Newt Scamander to lead an intrepid team.",
    poster: "https://image.tmdb.org/t/p/w500/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
    mediaService: "Hulu",
    continueWatching: false,
    progress: 0,
    trending: false,
    topRated: false,
    comingSoon: false
  }
];

// ─────────────────────────────────────────────────────────────
//  Media / Streaming Services
// ─────────────────────────────────────────────────────────────
const MEDIA_SERVICES = [
  { name: "Apple TV+", icon: "📺", color: "#000000" },
  { name: "HBO Max",   icon: "🎬", color: "#5822b4" },
  { name: "Peacock",   icon: "🦚", color: "#000000" },
  { name: "Disney+",   icon: "🏰", color: "#113ccf" },
  { name: "Hulu",      icon: "📗", color: "#1ce783" },
  { name: "Netflix",   icon: "🎥", color: "#e50914" },
  { name: "Prime",     icon: "📦", color: "#00a8e1" }
];

// ─────────────────────────────────────────────────────────────
//  Genre List
// ─────────────────────────────────────────────────────────────
const GENRES = [
  "Action",
  "Comedy",
  "Drama",
  "Romance",
  "Horror",
  "Historical",
  "Western",
  "Sci-Fi",
  "Adventure",
  "Thriller",
  "Animation",
  "Fantasy",
  "Crime",
  "Mystery"
];
